#pragma once
#define CONFIG_HOXPI_ETH_RMII 1
#define CONFIG_HOXPI_CAN_TX_GPIO 5
#define CONFIG_HOXPI_CAN_RX_GPIO 35
#define CONFIG_HOXPI_POLL_INTERVAL_S 30
#define CONFIG_HOXPI_POLL_DELAY_MS 100
#define CONFIG_HOXPI_MODBUS_PORT 502
#define CONFIG_HOXPI_ENABLE_WRITE 0
#define CONFIG_HOXPI_ETH_PHY_ADDR 0
#define CONFIG_HOXPI_ETH_PHY_RST_GPIO -1
#define CONFIG_HOXPI_ETH_MDC_GPIO 23
#define CONFIG_HOXPI_ETH_MDIO_GPIO 18
#define CONFIG_HOXPI_W5500_MISO 12
#define CONFIG_HOXPI_W5500_MOSI 11
#define CONFIG_HOXPI_W5500_SCLK 13
#define CONFIG_HOXPI_W5500_CS 14
#define CONFIG_HOXPI_W5500_INT 10
#define CONFIG_HOXPI_W5500_RST 9
